import { StyleSheet } from "react-native";
import Colors from "../../constants/Colors";

export default StyleSheet.create({
  headerContainer: {
    marginTop: 30,
    flexDirection: "row",
    // borderWidth: 1,
    // borderColor: "red",
    justifyContent: "space-around",
  },
  profilePicContainer: {
    flexDirection: "row",
  },
  profileIconCircle: {
    // borderWidth: 1,
    // borderColor: Colors.darkGreen,
    // width: 80,
    // height: 80,
    // borderRadius: 80 / 2,
    // overflow: "hidden",
    // alignSelf: "center",
    width: 80,
    height: 80,
    borderRadius: 80 / 2,
    overflow: "hidden",
    alignItems: "center",
    top: 10,
  },
  initials: {
    flexDirection: "row",
  },
  initialsFont: {
    fontFamily: "poppins-medium",
    color: Colors.darkGreen,
    fontSize: 40,
  },
  imageContainer: {
    backgroundColor: Colors.darkGray,
    height: 80,
    width: 80,
    borderRadius: 80 / 2,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    borderColor: Colors.darkGreen,
    borderWidth: 1,
  },
  changeProfilePicButton: {
    backgroundColor: Colors.lightGreen,
    width: 30,
    height: 30,
    borderRadius: 30 / 2,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    top: 50,
    left: 50,
  },
  userName: {
    fontSize: 24,
    fontFamily: "poppins-medium",
    color: Colors.textColor,
    marginTop: 15,
  },
  pointsContainer: {
    backgroundColor: Colors.darkGreen,
    marginTop: 30,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  userPoints: {
    color: "white",
    fontFamily: "poppins-medium",
    fontSize: 24,
    textAlign: "center",
  },
  pointsText: {
    color: "white",
    fontFamily: "poppins",
    fontSize: 16,
    textAlign: "center",
  },
  contentContainer: {
    backgroundColor: "white",
    height: "100%",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingTop: 50,
  },
  calendar: {
    marginBottom: 50,
  },
  calendarMonthText: {
    color: Colors.textColor,
    fontFamily: "poppins",
    fontSize: 16,
    marginRight: 25,
  },
  calendarDatesContainer: {
    marginTop: 25,
    marginRight: 20,
    backgroundColor: Colors.lightGray,
    width: 50,
    height: 75,
    justifyContent: "center",
    borderRadius: 10,
    // padding: 20,
  },
  calendarDateNumber: {
    color: Colors.textColor,
    textAlign: "center",
    marginBottom: 3,
    fontFamily: "poppins",
    fontSize: 16,
  },
  calendarDateDay: {
    color: Colors.textColor,
    textAlign: "center",
    fontFamily: "poppins",
  },
  choresTitle: {
    fontSize: 16,
    fontFamily: "poppins-medium",
    color: Colors.textColor,
    marginBottom: 3,
  },
  choresSubTitle: {
    fontFamily: "poppins",
    color: Colors.darkGray,
  },
});
